esphome:
  name: m5card
  friendly_name: M5 Cardputer

external_components:
  - source: github://pzich/esphome@cardputer
    refresh: 0min
    components: [74hc138, matrix_keypad]

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

logger:

api:
  reboot_timeout: 0s

ota:
  - platform: esphome
    password: "p4ssw0rd"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

spi:
  clk_pin: GPIO36
  mosi_pin: GPIO35
  miso_pin: GPIO39

display:
  platform: st7789v
  model: TTGO TDisplay 135x240
  backlight_pin: GPIO38
  cs_pin: GPIO37
  dc_pin: GPIO34
  reset_pin: GPIO33
  rotation: 90
  update_interval: 0.1s
  lambda: |-
    int key = id(matrix).get_pressed_key();
    int width = id(matrix).get_width();
    int r = key / width;
    int c = (key % width) * 2 + (r >= 4);
    r %= 4;

    for (uint8_t row = 0; row < 4; row++) {
      it.line(0, (row + 1) * 17, 237, (row + 1) * 17);

      for (uint8_t col = 0; col < 14; col++) {
        if (row == 0 && col != 0)
          it.line(col * 17, 0, col * 17, 68);

        if (row == r && col == c)
          it.filled_rectangle(col * 17, row * 17, 17, 17, COLOR_ON);
      }
    }

74hc138:
  id: rows
  address:
    - pin: GPIO08
    - pin: GPIO09
    - pin: GPIO11

matrix_keypad:
  id: matrix
  has_diodes: true
  rows:
    - pin:
        74hc138: rows
        number: 7
    - pin:
        74hc138: rows
        number: 6
    - pin:
        74hc138: rows
        number: 5
    - pin:
        74hc138: rows
        number: 4
    - pin:
        74hc138: rows
        number: 3
    - pin:
        74hc138: rows
        number: 2
    - pin:
        74hc138: rows
        number: 1
    - pin:
        74hc138: rows
        number: 0
  columns:
    - pin: GPIO13
    - pin: GPIO15
    - pin: GPIO03
    - pin: GPIO04
    - pin: GPIO05
    - pin: GPIO06
    - pin: GPIO07
